name: Test WBNB Balance

on:
  workflow_dispatch:    # So you can manually trigger it anytime

jobs:
  run-test-balance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install web3

      - name: Run test_balance.js script
        run: node test_balance.js
